import { gql } from "apollo-server-express";

export const examTypeDefs = gql`
  # ============================================
  # ENUMS (Exam-specific)
  # ============================================

  enum ExamDifficultyLevel {
    EASY
    MEDIUM
    HARD
  }

  enum ExamRegistrationStatusEnum {
    PENDING
    APPROVED
    REJECTED
  }

  enum ExamStatusEnum {
    PENDING_APPROVAL
    ACTIVE
    COMPLETED
    CANCELLED
  }

  enum ExamQuestionType {
    QUICK_TRUE_FALSE
    EXPANDED_TRUE_FALSE
    SINGLE_SELECT
    MULTI_SELECT
    VERY_SHORT_ANSWER
    SHORT_ANSWER
    LONG_ANSWER
  }

  enum ExamQuestionSpecialty {
    EPIDEMIOLOGY
    BIOSTATISTICS
    RESEARCH_METHODS
  }

  # ============================================
  # CORE TYPES (Exam-specific)
  # ============================================

  type ExamPreRegistrationDetail {
    id: ID!
    sessionId: String
    userId: String
    name: String
    emailAddress: String
    email: String
    courseTaken: String
    level: String
    registeredAt: String
    responses: String
    status: ExamRegistrationStatusEnum!
    approvalToken: String
    registeredVia: String
    approvedAt: String
  }

  type ExamResponse {
    questionId: ID!
    participantId: ID!
    response: String!
    isCorrect: Boolean
    questionType: ExamQuestionType
    additionalResponses: [String]
  }

  type ExamSessionRegistration {
    id: ID!
    sessionId: String!
    email: String!
    name: String!
    courseTaken: String!
    level: String!
    registeredAt: String!
    status: ExamRegistrationStatusEnum!
    approvalToken: String!
    approvedAt: String
    registeredVia: String
  }

  type ExamWaitingListResponse {
    registrations: [ExamPreRegistrationDetail!]!
    totalCount: Int!
    pendingCount: Int!
    approvedCount: Int!
    rejectedCount: Int!
  }

  type ExamAccessCheckResponse {
    hasAccess: Boolean!
    isSessionOpen: Boolean!
    isTimeReached: Boolean!
    message: String!
    examDetails: ExamQRDetails
  }

  type Exam {
    id: ID!
    title: String!
    sessionId: String!
    accessKey: String!
    questions: [ExamQuestion!]!
    difficultyDistribution: [ExamDifficultyLevel!]!
    examDate: String!
    timeZone: String!
    participants: [ExamPreRegistrationDetail!]!
    createdBy: ExamUser!
    createdAt: String!
    examPreRegistrationDetails: [ExamPreRegistrationDetail!]
    questionIdsUsed: [ID!]!
    specialty: ExamQuestionSpecialty
    topic: [String]
    difficulty: [ExamDifficultyLevel]
    examResponses: [ExamResponse]
    questionType: [ExamQuestionType]
    isAutoGenerated: Boolean
    maxParticipants: Int
    status: ExamStatusEnum
    qrPdfPath: String
    waitingList: [ExamSessionRegistration!]
    admittedParticipants: [ExamPreRegistrationDetail!]
    isSessionOpen: Boolean
    sessionStartTime: String
    sessionEndTime: String
    availableSpots: Int
    isFull: Boolean
    participantCount: Int
    pendingRegistrationsCount: Int
    approvedRegistrationsCount: Int
    rejectedRegistrationsCount: Int
  }

  type ExamQuestion {
    id: ID!
    text: String!
    questionType: ExamQuestionType!
    specialty: ExamQuestionSpecialty
    topic: [String]
    difficulty: ExamDifficultyLevel
    options: [String]
    correctAnswer: String
    explanation: String
  }

  type ExamUser {
    id: ID!
    personalInfo: ExamPersonalInfo
  }

  type ExamPersonalInfo {
    email: String
    fullName: String
  }

  type ExamQRCodeData {
    qrCodePdf: String!
    registrationUrl: String!
    examDetails: ExamQRDetails!
  }

  type ExamQRDetails {
    title: String!
    date: String!
    timeZone: String!
    sessionId: String!
  }

  # ============================================
  # NAMESPACED RESPONSE TYPES
  # ============================================

  type ExamApprovalResponse {
    success: Boolean!
    message: String!
  }

  type CreateExamSessionResponse {
    exam: Exam!
    joinUrl: String!
    qrCodeUrl: String!
    qrCodePdf: String!
    sessionId: String!
    accessKey: String!
    examId: ID!
  }

  type ExamRegistrationStatusResponse {
    isRegistered: Boolean!
    status: String
    registeredAt: String
    accessKey: String
  }

  type ExamRegistrationResponse {
    success: Boolean!
    message: String!
    registrationId: ID
    examId: ID
    status: ExamRegistrationStatusEnum
    approvalToken: String
    sessionId: String
  }

  # ============================================
  # INPUT TYPES
  # ============================================

  input ExamQuestionTypeCounts {
    QUICK_TRUE_FALSE: Int
    EXPANDED_TRUE_FALSE: Int
    SINGLE_SELECT: Int
    MULTI_SELECT: Int
    VERY_SHORT_ANSWER: Int
    SHORT_ANSWER: Int
    LONG_ANSWER: Int
  }

  input ExamPreRegistrationInput {
    userId: ID!
    name: String!
    emailAddress: String!
    courseTaken: String!
    level: String!
  }

  input ExamInput {
    title: String!
    difficultyDistribution: [ExamDifficultyLevel!]!
    examDate: String!
    timeZone: String!
    createdBy: ID!
    questionIds: [ID!]
    participants: [String]
    specialty: ExamQuestionSpecialty
    topic: [String]
    difficulty: [ExamDifficultyLevel]
    questionType: [ExamQuestionType]
    questionTypeCounts: ExamQuestionTypeCounts
    maxParticipants: Int
  }

  input ExamUserRegistrationInput {
    userId: String
    name: String!
    emailAddress: String!
    courseTaken: String!
    level: String!
  }

  input ExamRegistrationInput {
    encryptedData: String!
    userDetails: ExamUserRegistrationInput!
  }

  input RegisterForExamSessionInput {
    sessionId: String!
    email: String!
    name: String
    courseTaken: String
    level: String
  }

  # ============================================
  # QUERIES
  # ============================================

  type Query {
    getExamById(id: ID!): Exam
    getAllExams: [Exam]
    getExamByAccessKey(accessKey: String!): Exam
    getExamBySessionId(sessionId: String!): Exam
    getRecentQuizSessions(userId: String!): [Exam!]!
    getParticipatingExams(userId: String!): [Exam]
    getRecentExamSessions(userId: String!): [Exam!]!
    getPendingRegistrations(examId: ID!): [ExamPreRegistrationDetail!]!
    checkExamRegistrationStatus(
      examId: ID!
      email: String!
    ): ExamRegistrationResponse!
    getExamWaitingList(examId: ID!): ExamWaitingListResponse!
    checkExamSessionAccess(
      sessionId: String!
      email: String!
    ): ExamAccessCheckResponse!
    getExamSessionByInviteCode(inviteCode: String!): Exam
  }

  # ============================================
  # MUTATIONS
  # ============================================
  type Mutation {
    # Exam lifecycle
    createExam(input: ExamInput!): Exam!
    updateExam(examId: ID!, input: ExamInput!): Exam!
    deleteExam(examId: ID!): Boolean!
    openExamSession(examId: ID!): Exam!
    closeExamSession(examId: ID!): Exam!

    # Registration & participation
    registerForExam(input: ExamRegistrationInput!): ExamRegistrationResponse!
    registerForExamGroupSession(
      input: RegisterForExamSessionInput!
    ): ExamRegistrationResponse!
    manageExamRegistrations(
      examId: ID!
      registrationIds: [ID!]!
      action: String! # e.g. APPROVE or REJECT
    ): ExamApprovalResponse!
    manageExamParticipant(
      examId: ID!
      token: String!
      action: String!
    ): ExamApprovalResponse!
    addParticipantsToExam(examId: ID!, participantIds: [ID!]!): Exam!
    addExamPreRegistrationDetails(preRegistrations: String!): Exam!

    # Communication & utilities
    generateExamQRCode(examId: ID!): ExamQRCodeData!
    resendExamSessionQRCode(
      examId: ID!
      email: String!
    ): ExamRegistrationResponse!
    sendExamSessionReminders(examId: ID!): ExamApprovalResponse!

    # Group revision sessions
    createGroupRevisionSession(input: ExamInput!): CreateExamSessionResponse!
  }
`;

export default examTypeDefs;
