// resolvers/examResolvers/mutations.ts - COMPLETE FIXED VERSION
import mongoose, { Types } from "mongoose";
import crypto from "crypto";
import * as fs from "fs";
import fsp from "fs/promises";
import { promises as fsPromises } from "fs";
import path from "path";
import QRCode from "qrcode";
import Exam from "../../../models/Exam";
import Question from "../../../models/Question";
import User from "../../../models/User";
import { generateUniqueCode } from "../../../utils/identifier_generator";
import generateAccessKey from "../../../utils/accessKeyUtility";
import { sendEmail, EmailOptions } from "../../../utils/emailHandler";
import {
  encryptData,
  decryptData,
  sendApprovalEmail,
  sendRejectionEmail,
  generateExamAccessUrl,
  sendSessionReminderEmail,
} from "./helpers";
import { transformExam, getConvenerDetails } from "./helpers";
import { ExamInput, RegistrationStatusEnum } from "./types";

const ROOT_DIR = process.cwd();
const TMP_DIR = path.join(ROOT_DIR, "temp", "qrcodes");
const ASSETS_DIR = path.join(ROOT_DIR, "assets");

async function ensureDir(dir: string) {
  await fsPromises.mkdir(dir, { recursive: true });
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await fsPromises.access(p);
    return true;
  } catch {
    return false;
  }
}

async function generateQRCodeDataUrl(url: string): Promise<string> {
  return await QRCode.toDataURL(url, {
    width: 200,
    margin: 2,
    color: { dark: "#2A73C5", light: "#FFFFFF" },
  });
}

async function generateQRCodeBuffer(url: string): Promise<Buffer> {
  return await QRCode.toBuffer(url, {
    width: 750,
    margin: 1,
    errorCorrectionLevel: "H",
    color: { dark: "#2A73C5", light: "#FFFFFF" },
  });
}

function cleanTitle(title: string): string {
  return title
    .replace(/^\u200B/, "")
    .trimStart()
    .replace(/^GROUP_REVISION[\s\-_:\|]*\s*/i, "");
}

const examMutations = {
  Mutation: {
    async createExam(_: any, { input }: { input: ExamInput }) {
      try {
        if (!input.title) throw new Error("Title is required");

        const cleanedTitle = cleanTitle(input.title);
        let examDate: Date;

        if (typeof input.examDate === "string") {
          if (input.examDate.match(/^\d{4}-\d{2}-\d{2}$/)) {
            examDate = new Date(`${input.examDate}T12:00:00.000Z`);
          } else {
            examDate = new Date(input.examDate);
          }
        } else {
          examDate = new Date(input.examDate);
        }

        if (isNaN(examDate.getTime())) {
          throw new Error("Invalid exam date format");
        }

        const sessionId = generateUniqueCode(10);
        const accessKey = generateAccessKey();

        const exam = await Exam.create({
          title: cleanedTitle,
          difficultyDistribution: input.difficultyDistribution || [],
          examDate,
          timeZone: input.timeZone,
          createdBy: new Types.ObjectId(input.createdBy),
          questions:
            input.questionIds?.map((id) => new Types.ObjectId(id)) || [],
          questionIdsUsed: input.questionIds || [],
          participants: [],
          waitingList: [],
          admittedParticipants: [],
          sessionId,
          accessKey,
          examPreRegistrationDetails: [],
          specialty: input.specialty,
          topic: input.topic || [],
          difficulty: input.difficulty || [],
          questionType: input.questionType || [],
          isAutoGenerated: false,
          status: "PENDING_APPROVAL",
          isSessionOpen: false,
          sessionStartTime: examDate,
          maxParticipants: input.maxParticipants,
        });

        const populatedExam = await Exam.findById(exam._id)
          .populate(["questions", "createdBy"])
          .lean();

        // Safely access properties with type assertion
        const examData = populatedExam as any;
        const participants = examData?.participants || [];
        const transformedExam = transformExam(examData);

        return {
          ...transformedExam,
          participantCount: participants.length,
          approvedRegistrationsCount: participants.filter(
            (p: any) => p.status === "APPROVED",
          ).length,
          pendingRegistrationsCount: 0,
          rejectedRegistrationsCount: 0,
        };
      } catch (error: any) {
        console.error("Error in createExam:", error);
        throw new Error(error.message || "Failed to create exam");
      }
    },

    async updateExam(
      _: any,
      { examId, input }: { examId: string; input: ExamInput },
    ) {
      try {
        const exam = await Exam.findById(examId);
        if (!exam) throw new Error("Exam not found");

        const updateData: any = {};
        if (input.title) updateData.title = cleanTitle(input.title);
        if (input.difficultyDistribution)
          updateData.difficultyDistribution = input.difficultyDistribution;
        if (input.examDate) updateData.examDate = new Date(input.examDate);
        if (input.timeZone) updateData.timeZone = input.timeZone;
        if (input.questionIds)
          updateData.questions = input.questionIds.map(
            (id) => new Types.ObjectId(id),
          );
        if (input.specialty) updateData.specialty = input.specialty;
        if (input.topic) updateData.topic = input.topic;
        if (input.difficulty) updateData.difficulty = input.difficulty;
        if (input.questionType) updateData.questionType = input.questionType;
        if (input.maxParticipants !== undefined)
          updateData.maxParticipants = input.maxParticipants;

        const updatedExam = await Exam.findByIdAndUpdate(examId, updateData, {
          new: true,
        })
          .populate(["questions", "createdBy"])
          .lean();

        // Safely access properties with type assertion
        const examData = updatedExam as any;
        const participants = examData?.participants || [];
        const transformedExam = transformExam(examData);

        return {
          ...transformedExam,
          approvedRegistrationsCount: participants.filter(
            (p: any) => p.status === "APPROVED",
          ).length,
          participantCount: participants.length,
        };
      } catch (error: any) {
        console.error("Error in updateExam:", error);
        throw new Error(error.message || "Failed to update exam");
      }
    },

    async deleteExam(_: any, { examId }: { examId: string }) {
      try {
        const exam = await Exam.findByIdAndDelete(examId);
        if (!exam) throw new Error("Exam not found");
        return true;
      } catch (error: any) {
        console.error("Error in deleteExam:", error);
        throw new Error(error.message || "Failed to delete exam");
      }
    },

    async openExamSession(_: any, { examId }: { examId: string }) {
      try {
        const exam = await Exam.findById(examId);
        if (!exam) throw new Error("Session not found");

        const now = new Date();
        const examDate = new Date(exam.examDate);

        if (now < examDate) {
          throw new Error(
            `Session can only be opened at or after ${exam.examDate}`,
          );
        }

        exam.isSessionOpen = true;
        exam.status = "ACTIVE";
        await exam.save();

        // Notify all approved participants
        const approvedParticipants =
          exam.participants?.filter((p: any) => p.status === "APPROVED") || [];

        for (const participant of approvedParticipants) {
          try {
            const examAccessUrl = generateExamAccessUrl({
              sessionId: exam.sessionId,
              accessKey: exam.accessKey,
              email: participant.emailAddress || participant.email,
              expiresAt: exam.examDate,
            });

            await sendApprovalEmail({
              email: participant.emailAddress || participant.email,
              name: participant.name,
              examTitle: exam.title,
              examDate: exam.examDate,
              examUrl: examAccessUrl,
              accessKey: exam.accessKey,
              sessionId: exam.sessionId,
            });
          } catch (emailError) {
            console.error(
              `Failed to send email to ${participant.emailAddress}:`,
              emailError,
            );
          }
        }

        const populatedExam = await Exam.findById(examId)
          .populate(["questions", "createdBy"])
          .lean();

        // Safely access properties with type assertion
        const examData = populatedExam as any;
        const participants = examData?.participants || [];
        const transformedExam = transformExam(examData);

        return {
          ...transformedExam,
          approvedRegistrationsCount: participants.filter(
            (p: any) => p.status === "APPROVED",
          ).length,
          participantCount: participants.length,
        };
      } catch (error: any) {
        console.error("Error in openExamSession:", error);
        throw new Error(error.message || "Failed to open session");
      }
    },

    async closeExamSession(_: any, { examId }: { examId: string }) {
      try {
        const exam = await Exam.findById(examId);
        if (!exam) throw new Error("Session not found");

        exam.isSessionOpen = false;
        exam.status = "COMPLETED";
        await exam.save();

        const populatedExam = await Exam.findById(examId)
          .populate(["questions", "createdBy"])
          .lean();

        // Safely access properties with type assertion
        const examData = populatedExam as any;
        const participants = examData?.participants || [];
        const transformedExam = transformExam(examData);

        return {
          ...transformedExam,
          approvedRegistrationsCount: participants.filter(
            (p: any) => p.status === "APPROVED",
          ).length,
          participantCount: participants.length,
        };
      } catch (error: any) {
        console.error("Error in closeExamSession:", error);
        throw new Error(error.message || "Failed to close session");
      }
    },

    async registerForExam(
      _: any,
      { input }: { input: { encryptedData: string; userDetails: any } },
    ) {
      try {
        const decryptedData = decryptData(input.encryptedData);
        const { sessionId, email, name, courseTaken, level } =
          JSON.parse(decryptedData);

        const exam = await Exam.findOne({ sessionId });
        if (!exam) throw new Error("Exam session not found");

        const existingRegistration = exam.examPreRegistrationDetails?.find(
          (r: any) => r.email === email || r.emailAddress === email,
        );

        if (existingRegistration) {
          if (existingRegistration.status === "APPROVED") {
            return {
              success: true,
              message: "Already registered and approved",
              registrationId: existingRegistration.id,
              examId: exam._id.toString(),
              status: "APPROVED",
              approvalToken: existingRegistration.approvalToken,
              sessionId: exam.sessionId,
            };
          }
          return {
            success: false,
            message: `Registration ${existingRegistration.status.toLowerCase()}`,
            registrationId: existingRegistration.id,
            examId: exam._id.toString(),
            status: existingRegistration.status,
            approvalToken: null,
            sessionId: exam.sessionId,
          };
        }

        const approvalToken = crypto.randomBytes(32).toString("hex");
        const newRegistration = {
          id: new Types.ObjectId().toString(),
          sessionId: exam.sessionId,
          email,
          emailAddress: email,
          name: name || email.split("@")[0],
          courseTaken: courseTaken || "Not specified",
          level: level || "Not specified",
          registeredAt: new Date().toISOString(),
          status: "PENDING",
          approvalToken,
          registeredVia: "QR_CODE",
        };

        if (!exam.examPreRegistrationDetails)
          exam.examPreRegistrationDetails = [];
        exam.examPreRegistrationDetails.push(newRegistration);
        await exam.save();

        return {
          success: true,
          message: "Registration successful. Awaiting approval",
          registrationId: newRegistration.id,
          examId: exam._id.toString(),
          status: "PENDING",
          approvalToken,
          sessionId: exam.sessionId,
        };
      } catch (error: any) {
        console.error("Error in registerForExam:", error);
        throw new Error(error.message || "Failed to register for exam");
      }
    },

    async registerForExamGroupSession(_: any, { input }: { input: any }) {
      try {
        const { sessionId, email, name, courseTaken, level } = input;

        const exam = await Exam.findOne({ sessionId });
        if (!exam) throw new Error("Exam session not found");

        const existingRegistration = exam.examPreRegistrationDetails?.find(
          (r: any) => r.email === email || r.emailAddress === email,
        );

        if (existingRegistration) {
          if (existingRegistration.status === "APPROVED") {
            return {
              success: true,
              message: "Already registered and approved",
              registrationId: existingRegistration.id,
              examId: exam._id.toString(),
              status: "APPROVED",
              approvalToken: existingRegistration.approvalToken,
              sessionId: exam.sessionId,
            };
          }
          return {
            success: false,
            message: `Registration ${existingRegistration.status.toLowerCase()}`,
            registrationId: existingRegistration.id,
            examId: exam._id.toString(),
            status: existingRegistration.status,
            approvalToken: null,
            sessionId: exam.sessionId,
          };
        }

        const approvalToken = crypto.randomBytes(32).toString("hex");
        const newRegistration = {
          id: new Types.ObjectId().toString(),
          sessionId: exam.sessionId,
          email,
          emailAddress: email,
          name: name || email.split("@")[0],
          courseTaken: courseTaken || "Not specified",
          level: level || "Not specified",
          registeredAt: new Date().toISOString(),
          status: "PENDING",
          approvalToken,
          registeredVia: "QR_CODE",
        };

        if (!exam.examPreRegistrationDetails)
          exam.examPreRegistrationDetails = [];
        exam.examPreRegistrationDetails.push(newRegistration);
        await exam.save();

        return {
          success: true,
          message: "Registration successful. Awaiting approval",
          registrationId: newRegistration.id,
          examId: exam._id.toString(),
          status: "PENDING",
          approvalToken,
          sessionId: exam.sessionId,
        };
      } catch (error: any) {
        console.error("Error in registerForExamGroupSession:", error);
        throw new Error(error.message || "Failed to register for session");
      }
    },

    async manageExamRegistrations(
      _: any,
      {
        examId,
        registrationIds,
        action,
      }: { examId: string; registrationIds: string[]; action: string },
    ) {
      try {
        const exam = await Exam.findById(examId);
        if (!exam) throw new Error("Exam not found");

        const actionUpper = action.toUpperCase();
        if (actionUpper !== "APPROVE" && actionUpper !== "REJECT") {
          throw new Error("Action must be either 'approve' or 'reject'");
        }

        let processedCount = 0;
        let approvedCount =
          exam.participants?.filter((p: any) => p.status === "APPROVED")
            .length || 0;

        for (const regId of registrationIds) {
          const registration = exam.examPreRegistrationDetails?.find(
            (r: any) => r.id === regId,
          );
          if (!registration || registration.status !== "PENDING") continue;

          if (actionUpper === "APPROVE") {
            if (exam.maxParticipants && approvedCount >= exam.maxParticipants) {
              if (!exam.waitingList) exam.waitingList = [];
              exam.waitingList.push({
                id: new Types.ObjectId().toString(),
                sessionId: exam.sessionId,
                email: registration.email,
                name: registration.name,
                courseTaken: registration.courseTaken,
                level: registration.level,
                registeredAt: registration.registeredAt,
                status: "PENDING",
                approvalToken: registration.approvalToken,
                registeredVia: registration.registeredVia,
              });
              exam.examPreRegistrationDetails =
                exam.examPreRegistrationDetails?.filter(
                  (r: any) => r.id !== regId,
                );
            } else {
              registration.status = "APPROVED";
              registration.approvedAt = new Date().toISOString();

              if (!exam.participants) exam.participants = [];
              exam.participants.push({
                userId: registration.email,
                name: registration.name,
                emailAddress: registration.email,
                courseTaken: registration.courseTaken,
                level: registration.level,
                registeredAt: registration.registeredAt,
                responses: "",
                status: "APPROVED",
                approvalToken: registration.approvalToken,
                registeredVia: registration.registeredVia,
                approvedAt: registration.approvedAt,
              });

              approvedCount++;
              processedCount++;
            }
          } else if (actionUpper === "REJECT") {
            registration.status = "REJECTED";
            processedCount++;
          }
        }

        await exam.save();
        const actionLowered = actionUpper.toLowerCase();

        return {
          success: true,
          message: `${processedCount} registration(s) ${actionLowered}ed successfully`,
        };
      } catch (error: any) {
        console.error("Error in manageExamRegistrations:", error);
        throw new Error(error.message || "Failed to manage registrations");
      }
    },

    async manageExamParticipant(
      _: any,
      {
        examId,
        token,
        action,
      }: { examId: string; token: string; action: string },
    ) {
      try {
        const exam = await Exam.findById(examId);
        if (!exam) throw new Error("Exam not found");

        const participantIndex = exam.participants?.findIndex(
          (p: any) => p.approvalToken === token,
        );

        if (participantIndex === undefined || participantIndex === -1) {
          throw new Error("Participant not found");
        }

        const participant = exam.participants![participantIndex];
        const actionUpper = action.toUpperCase();
        const actionLowered = actionUpper.toLowerCase();

        if (actionUpper === "APPROVE") {
          participant.status = "APPROVED";
          participant.approvedAt = new Date().toISOString();

          const examAccessUrl = generateExamAccessUrl({
            sessionId: exam.sessionId,
            accessKey: exam.accessKey,
            email: participant.emailAddress,
            expiresAt: exam.examDate,
          });

          await sendApprovalEmail({
            email: participant.emailAddress,
            name: participant.name,
            examTitle: exam.title,
            examDate: exam.examDate,
            examUrl: examAccessUrl,
            accessKey: exam.accessKey,
            sessionId: exam.sessionId,
          });
        } else if (actionUpper === "REJECT") {
          participant.status = "REJECTED";
          await sendRejectionEmail({
            email: participant.emailAddress,
            name: participant.name,
            examTitle: exam.title,
          });
        } else {
          throw new Error("Action must be either 'approve' or 'reject'");
        }

        await exam.save();

        return {
          success: true,
          message: `Participant ${actionLowered}ed successfully`,
        };
      } catch (error: any) {
        console.error("Error in manageExamParticipant:", error);
        throw new Error(error.message || "Failed to manage participant");
      }
    },

    async addParticipantsToExam(
      _: any,
      { examId, participantIds }: { examId: string; participantIds: string[] },
    ) {
      try {
        const exam = await Exam.findById(examId);
        if (!exam) throw new Error("Exam not found");

        for (const participantId of participantIds) {
          const user = await User.findById(participantId).lean();
          if (
            user &&
            !exam.participants?.some((p: any) => p.userId === participantId)
          ) {
            if (!exam.participants) exam.participants = [];
            exam.participants.push({
              userId: participantId,
              name: user.personalInfo?.fullName || "User",
              emailAddress: user.personalInfo?.email,
              status: "PENDING",
              registeredAt: new Date().toISOString(),
            });
          }
        }

        await exam.save();

        const populatedExam = await Exam.findById(examId)
          .populate(["questions", "createdBy"])
          .lean();

        // Safely access properties with type assertion
        const examData = populatedExam as any;
        const participants = examData?.participants || [];
        const transformedExam = transformExam(examData);

        return {
          ...transformedExam,
          approvedRegistrationsCount: participants.filter(
            (p: any) => p.status === "APPROVED",
          ).length,
          participantCount: participants.length,
        };
      } catch (error: any) {
        console.error("Error in addParticipantsToExam:", error);
        throw new Error(error.message || "Failed to add participants");
      }
    },

    async addExamPreRegistrationDetails(
      _: any,
      { preRegistrations }: { preRegistrations: string },
    ) {
      try {
        const registrations = JSON.parse(preRegistrations);
        const examId = registrations[0]?.examId;

        const exam = await Exam.findById(examId);
        if (!exam) throw new Error("Exam not found");

        for (const reg of registrations) {
          if (!exam.examPreRegistrationDetails)
            exam.examPreRegistrationDetails = [];
          exam.examPreRegistrationDetails.push({
            id: new Types.ObjectId().toString(),
            sessionId: exam.sessionId,
            userId: reg.userId,
            name: reg.name,
            emailAddress: reg.emailAddress,
            courseTaken: reg.courseTaken,
            level: reg.level,
            registeredAt: new Date().toISOString(),
            status: "PENDING",
            approvalToken: crypto.randomBytes(32).toString("hex"),
            registeredVia: "BULK_UPLOAD",
          });
        }

        await exam.save();
        return exam;
      } catch (error: any) {
        console.error("Error in addExamPreRegistrationDetails:", error);
        throw new Error(error.message || "Failed to add pre-registrations");
      }
    },

    async generateExamQRCode(_: any, { examId }: { examId: string }) {
      try {
        const exam = await Exam.findById(examId);
        if (!exam) throw new Error("Exam not found");

        const registrationUrl = `${process.env.FRONTEND_URL || "http://localhost:8000"}/join-session/${exam.sessionId}`;
        const qrCodePdf = await generateQRCodeDataUrl(registrationUrl);

        return {
          qrCodePdf,
          registrationUrl,
          examDetails: {
            title: exam.title,
            date: exam.examDate.toISOString(),
            timeZone: exam.timeZone || "UTC",
            sessionId: exam.sessionId,
          },
        };
      } catch (error: any) {
        console.error("Error in generateExamQRCode:", error);
        throw new Error(error.message || "Failed to generate QR code");
      }
    },

    async resendExamSessionQRCode(
      _: any,
      { examId, email }: { examId: string; email: string },
    ) {
      try {
        const exam = await Exam.findById(examId);
        if (!exam) throw new Error("Exam not found");

        const creator = await User.findOne({ "personalInfo.email": email });
        if (!creator) throw new Error("Creator not found");

        const registrationUrl = `${process.env.FRONTEND_URL || "http://localhost:8000"}/join-session/${exam.sessionId}`;

        return {
          success: true,
          message: "QR code resent successfully",
          registrationId: exam._id.toString(),
          examId: exam._id.toString(),
          status: "PENDING",
          approvalToken: exam.accessKey,
          sessionId: exam.sessionId,
        };
      } catch (error: any) {
        console.error("Error in resendExamSessionQRCode:", error);
        throw new Error(error.message || "Failed to resend QR code");
      }
    },

    async sendExamSessionReminders(_: any, { examId }: { examId: string }) {
      try {
        const exam = await Exam.findById(examId);
        if (!exam) throw new Error("Exam not found");

        const approvedParticipants =
          exam.participants?.filter((p: any) => p.status === "APPROVED") || [];
        let reminderCount = 0;

        for (const participant of approvedParticipants) {
          const examAccessUrl = generateExamAccessUrl({
            sessionId: exam.sessionId,
            accessKey: exam.accessKey,
            email: participant.emailAddress,
            expiresAt: exam.examDate,
          });

          await sendSessionReminderEmail({
            email: participant.emailAddress,
            name: participant.name,
            examTitle: exam.title,
            examDate: exam.examDate,
            examUrl: examAccessUrl,
            accessKey: exam.accessKey,
            sessionId: exam.sessionId,
          });
          reminderCount++;
        }

        return {
          success: true,
          message: `Reminders sent to ${reminderCount} participant(s)`,
        };
      } catch (error: any) {
        console.error("Error in sendExamSessionReminders:", error);
        throw new Error(error.message || "Failed to send reminders");
      }
    },

    async createGroupRevisionSession(_: any, { input }: { input: ExamInput }) {
      try {
        if (!input.title) throw new Error("Title is required");

        const cleanedTitle = cleanTitle(input.title);
        let examDate: Date;

        if (typeof input.examDate === "string") {
          if (input.examDate.match(/^\d{4}-\d{2}-\d{2}$/)) {
            examDate = new Date(`${input.examDate}T12:00:00.000Z`);
          } else {
            examDate = new Date(input.examDate);
          }
        } else {
          examDate = new Date(input.examDate);
        }

        if (isNaN(examDate.getTime())) {
          throw new Error("Invalid exam date format");
        }

        if (examDate <= new Date()) {
          throw new Error("Exam must be in the future");
        }

        let questionIds: Types.ObjectId[] = [];

        if (input.questionIds && input.questionIds.length > 0) {
          questionIds = input.questionIds.map((id) => new Types.ObjectId(id));
        } else if (input.questionTypeCounts) {
          const query: any = {};
          if (input.specialty) query.specialty = input.specialty;
          if (input.topic && input.topic.length > 0)
            query.topic = { $in: input.topic };
          if (input.difficulty && input.difficulty.length > 0)
            query.difficulty = { $in: input.difficulty };
          if (input.questionType && input.questionType.length > 0)
            query.questionType = { $in: input.questionType };

          const questionsByType: { [key: string]: Types.ObjectId[] } = {};

          for (const [type, count] of Object.entries(
            input.questionTypeCounts,
          )) {
            if (count > 0) {
              const typeQuery = { ...query, questionType: type };
              const questions = await Question.find(typeQuery).limit(
                count as number,
              );
              questionsByType[type] = questions.map((q) => q._id);
            }
          }

          questionIds = Object.values(questionsByType).flat();

          if (questionIds.length === 0) {
            throw new Error(
              "No questions found matching the specified criteria",
            );
          }
        } else {
          throw new Error(
            "Either provide questionIds or questionTypeCounts for auto-generation",
          );
        }

        const sessionId = generateUniqueCode(10);
        const accessKey = generateAccessKey();
        const joinUrl = `${process.env.FRONTEND_URL || "http://localhost:8000"}/join-session/${sessionId}`;

        const exam = await Exam.create({
          title: cleanedTitle,
          difficultyDistribution: input.difficultyDistribution || [],
          examDate,
          timeZone: input.timeZone,
          createdBy: new Types.ObjectId(input.createdBy),
          questions: questionIds,
          questionIdsUsed: questionIds,
          participants: [],
          waitingList: [],
          admittedParticipants: [],
          sessionId,
          accessKey,
          examPreRegistrationDetails: [],
          specialty: input.specialty,
          topic: input.topic || [],
          difficulty: input.difficulty || [],
          questionType: input.questionType || [],
          isAutoGenerated: !!input.questionTypeCounts,
          status: "PENDING_APPROVAL",
          isSessionOpen: false,
          sessionStartTime: examDate,
          maxParticipants: input.maxParticipants,
        });

        const populatedExam = await Exam.findById(exam._id)
          .populate(["questions", "createdBy"])
          .lean();

        const qrCodeUrl = await generateQRCodeDataUrl(joinUrl);
        const examData = populatedExam as any;
        const transformedExam = transformExam(examData);

        return {
          exam: {
            ...transformedExam,
            participantCount: 0,
            approvedRegistrationsCount: 0,
            pendingRegistrationsCount: 0,
            rejectedRegistrationsCount: 0,
          },
          joinUrl,
          qrCodeUrl,
          qrCodePdf: "",
          sessionId,
          accessKey,
          examId: exam._id.toString(),
        };
      } catch (error: any) {
        console.error("Error in createGroupRevisionSession:", error);
        throw new Error(
          error.message || "Failed to create group revision session",
        );
      }
    },
  },
};

export default examMutations;
