// src/types/examTypes.ts

export interface Exam {
  id: string;
  title: string;
  sessionId: string;
  accessKey: string;
  questions: Question[];
  difficultyDistribution: DifficultyLevel[];
  examDate: string;
  timeZone: string;
  participants: PreRegistrationDetail[];
  createdBy: User;
  createdAt: string;
  examPreRegistrationDetails?: PreRegistrationDetail[];
  questionIdsUsed?: string[];
  specialty?: QuestionSpecialty;
  topic?: string[];
  difficulty?: DifficultyLevel[];
  examResponses?: ExamResponse[];
  questionType?: QuestionType[];
  isAutoGenerated?: boolean;
  maxParticipants?: number;
  status?: ExamStatusEnum;
  qrPdfPath?: string;
  waitingList?: SessionRegistration[];
  admittedParticipants?: PreRegistrationDetail[];
  isSessionOpen?: boolean;
  sessionStartTime?: string;
  sessionEndTime?: string;

  // Virtual/computed fields
  availableSpots?: number;
  isFull?: boolean;
  participantCount?: number;
  pendingRegistrationsCount?: number;
  approvedRegistrationsCount?: number;
  rejectedRegistrationsCount?: number;
}

// LeanExam is the MongoDB lean document version of Exam
export type LeanExam = Exam & {
  _id: any;
  __v?: number;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

// Export missing types
export interface ExamRegistrationInput {
  sessionId: string;
  email: string;
  name?: string;
  courseTaken?: string;
  level?: string;
}

export type RegistrationStatusEnum = "PENDING" | "APPROVED" | "REJECTED";
export type RegisteredVia = "QR_CODE" | "EMAIL" | "MANUAL" | "LINK";

// Re-export existing types if needed
export interface PreRegistrationDetail {
  userId?: string;
  name?: string;
  emailAddress?: string;
  courseTaken?: string;
  level?: string;
  registeredAt?: Date | string;
  responses?: string;
  status?: RegistrationStatusEnum;
  approvalToken?: string;
  registeredVia?: string;
  approvedAt?: Date | string;
}

export interface SessionRegistration {
  id: string;
  sessionId: string;
  email: string;
  name: string;
  courseTaken: string;
  level: string;
  registeredAt: Date | string;
  status: RegistrationStatusEnum;
  approvalToken: string;
  approvedAt?: Date | string;
  registeredVia?: RegisteredVia;
}

// Import the enum from your main types

export interface Question {
  id: string;
  shortId: string;
  stem: string;
  questionType: QuestionType;
  difficulty: DifficultyLevel;
  choices?: string[];
  correctAnswers?: string[];
  explanation?: string;
  specialty?: string;
  topic?: string[];
  createdAt?: string;
  metrics?: QuestionMetrics;
}

export interface QuestionMetrics {
  timesAttempted: number;
  timesCorrect: number;
  timesPartiallyCorrect: number;
  timesIncorrect: number;
  averageTimeSeconds: number;
  lastAnsweredAt?: string;
  confidenceScore?: number;
}

export interface User {
  id: string;
  personalInfo: {
    username?: string;
    fullName?: string;
    email?: string;
  };
}

export interface ExamResponse {
  questionId: string;
  participantId: string;
  response: string;
  isCorrect: boolean;
  questionType: QuestionType;
  additionalResponses?: string[];
}

export interface WaitingListResponse {
  registrations: SessionRegistration[];
  totalCount: number;
  pendingCount: number;
  approvedCount: number;
  rejectedCount: number;
}

export interface AccessCheckResponse {
  hasAccess: boolean;
  isSessionOpen: boolean;
  isTimeReached: boolean;
  message: string;
  examDetails?: ExamQRDetails;
}

export interface CreateSessionResponse {
  exam: Exam;
  joinUrl: string;
  qrCodeUrl: string;
  qrCodePdf: string;
  sessionId: string;
  accessKey: string;
  examId: string;
}

export interface RegistrationResponse {
  success: boolean;
  message: string;
  status: string;
  accessKey?: string;
}

export interface ApprovalResponse {
  success: boolean;
  message: string;
}

export interface RegisterForSessionInput {
  sessionId: string;
  email: string;
  name?: string;
  courseTaken?: string;
  level?: string;
}

export interface ExamInput {
  title: string;
  difficultyDistribution: DifficultyLevel[];
  examDate: string;
  timeZone: string;
  createdBy: string;
  questionIds?: string[];
  participants?: string[];
  specialty?: QuestionSpecialty;
  topic?: string[];
  difficulty?: DifficultyLevel[];
  questionType?: QuestionType[];
  questionTypeCounts?: QuestionTypeCounts;
  maxParticipants?: number;
}

export interface QuestionTypeCounts {
  QUICK_TRUE_FALSE?: number;
  EXPANDED_TRUE_FALSE?: number;
  SINGLE_SELECT?: number;
  MULTI_SELECT?: number;
  VERY_SHORT_ANSWER?: number;
  SHORT_ANSWER?: number;
  LONG_ANSWER?: number;
}

export interface ExamQRDetails {
  title: string;
  date: string;
  timeZone: string;
  sessionId: string;
}

export type DifficultyLevel = "EASY" | "MEDIUM" | "HARD";
export type ExamStatusEnum =
  | "PENDING_APPROVAL"
  | "ACTIVE"
  | "COMPLETED"
  | "CANCELLED";
export type QuestionType =
  | "QUICK_TRUE_FALSE"
  | "EXPANDED_TRUE_FALSE"
  | "SINGLE_SELECT"
  | "MULTI_SELECT"
  | "VERY_SHORT_ANSWER"
  | "SHORT_ANSWER"
  | "LONG_ANSWER";

export type QuestionSpecialty =
  | "EPIDEMIOLOGY"
  | "BIOSTATISTICS"
  | "RESEARCH_METHODS";
