export enum Locality {
  NORSE = "NORSE",
  CELTIC = "CELTIC",
  GREEK = "GREEK",
  ROMAN = "ROMAN",
  EGYPTIAN = "EGYPTIAN",
  MESOAMERICAN = "MESOAMERICAN",
  AFRICAN = "AFRICAN",
}

export enum Role {
  ADMIN = "ADMIN",
  FACILITATOR = "FACILITATOR",
  FACULTY = "FACULTY",
  STUDENT = "STUDENT",
}
