import mongoose, { Schema, Document, Types } from "mongoose";

// ============================================
// ENUMS (Matching SDL exactly)
// ============================================

export type DifficultyLevel = "EASY" | "MEDIUM" | "HARD";
export type RegistrationStatus = "PENDING" | "APPROVED" | "REJECTED";
export type ExamStatus =
  | "PENDING_APPROVAL"
  | "ACTIVE"
  | "COMPLETED"
  | "CANCELLED";
export type WaitingListStatus = "PENDING" | "APPROVED" | "REJECTED";
export type QuestionType =
  | "QUICK_TRUE_FALSE"
  | "EXPANDED_TRUE_FALSE"
  | "SINGLE_SELECT"
  | "MULTI_SELECT"
  | "VERY_SHORT_ANSWER"
  | "SHORT_ANSWER"
  | "LONG_ANSWER";
export type QuestionSpecialty =
  | "EPIDEMIOLOGY"
  | "BIOSTATISTICS"
  | "RESEARCH_METHODS";

// ============================================
// INTERFACES (Matching SDL types)
// ============================================

// Interface for PreRegistrationDetail (matches SDL PreRegistrationDetail type)
export interface IPreRegistrationDetail {
  _id?: Types.ObjectId;
  sessionId?: string;
  userId?: string;
  name?: string;
  emailAddress?: string;
  email?: string; // Added to match SDL (has both emailAddress and email)
  courseTaken?: string;
  level?: string;
  registeredAt?: Date;
  responses?: string;
  status?: RegistrationStatus;
  approvalToken?: string;
  registeredVia?: string;
  approvedAt?: Date;
}

// Interface for ExamResponse (matches SDL ExamResponse type)
export interface IExamResponse {
  questionId: Types.ObjectId;
  participantId: string;
  response: string;
  isCorrect?: boolean;
  questionType?: QuestionType;
  additionalResponses?: string[];
}

// Interface for SessionRegistration (matches SDL SessionRegistration type)
export interface ISessionRegistration {
  _id?: Types.ObjectId;
  sessionId: string;
  email: string;
  name: string;
  courseTaken: string;
  level: string;
  registeredAt: Date;
  status: WaitingListStatus;
  approvalToken: string;
  approvedAt?: Date;
  registeredVia?: string;
}

// Interface for Exam (matches SDL Exam type)
export interface IExam extends Document {
  // Core fields
  id: string;
  title: string;
  sessionId: string;
  accessKey: string;
  questions: Types.ObjectId[];
  difficultyDistribution: DifficultyLevel[];
  examDate: Date;
  timeZone: string;
  participants: IPreRegistrationDetail[];
  createdBy: Types.ObjectId;
  createdAt: Date;

  // Optional fields (matches SDL)
  examPreRegistrationDetails?: IPreRegistrationDetail[];
  questionIdsUsed?: Types.ObjectId[];
  specialty?: QuestionSpecialty;
  topic?: string[];
  difficulty?: DifficultyLevel[];
  examResponses?: IExamResponse[];
  questionType?: QuestionType[];
  isAutoGenerated?: boolean;
  maxParticipants?: number;
  status?: ExamStatus;
  qrPdfPath?: string;

  // New fields for session workflow (matches SDL)
  waitingList?: ISessionRegistration[];
  admittedParticipants?: IPreRegistrationDetail[];
  isSessionOpen?: boolean;
  sessionStartTime?: Date;
  sessionEndTime?: Date;

  // Timestamps
  updatedAt: Date;

  // Virtual/computed fields
  availableSpots?: number;
  isFull?: boolean;
  participantCount?: number;
  pendingRegistrationsCount?: number;
  approvedRegistrationsCount?: number;
  rejectedRegistrationsCount?: number;

  // Instance methods
  isRegistrationFull(): boolean;
  addToWaitingList(
    registrationData: Partial<ISessionRegistration>,
  ): Promise<ISessionRegistration>;
  approveWaitingListEntry(
    registrationId: string,
  ): Promise<ISessionRegistration | null>;
  rejectWaitingListEntry(
    registrationId: string,
  ): Promise<ISessionRegistration | null>;
  admitFromWaitingList(
    registrationId: string,
  ): Promise<IPreRegistrationDetail | null>;
  getWaitingListStats(): {
    total: number;
    pending: number;
    approved: number;
    rejected: number;
  };
  checkAccess(email: string): {
    hasAccess: boolean;
    isSessionOpen: boolean;
    isTimeReached: boolean;
    message: string;
  };
}

// ============================================
// SUB-SCHEMAS
// ============================================

// PreRegistrationDetail Schema (matches SDL PreRegistrationDetail type)
const PreRegistrationDetailSchema = new Schema<IPreRegistrationDetail>(
  {
    sessionId: { type: String, trim: true },
    userId: { type: String, trim: true },
    name: { type: String, trim: true },
    emailAddress: { type: String, trim: true, lowercase: true },
    email: { type: String, trim: true, lowercase: true }, // Added to match SDL
    courseTaken: { type: String, trim: true },
    level: { type: String, trim: true },
    registeredAt: { type: Date, default: Date.now },
    responses: { type: String, trim: true, default: "" },
    status: {
      type: String,
      enum: ["PENDING", "APPROVED", "REJECTED"],
      default: "PENDING",
    },
    approvalToken: { type: String, trim: true },
    registeredVia: {
      type: String,
      enum: ["QR_CODE", "MANUAL", "EMAIL_FORM"],
      default: "MANUAL",
    },
    approvedAt: { type: Date },
  },
  { _id: true },
);

// ExamResponse Schema (matches SDL ExamResponse type)
const ExamResponseSchema = new Schema<IExamResponse>(
  {
    questionId: {
      type: Schema.Types.ObjectId,
      required: true,
      ref: "Question",
    },
    participantId: { type: String, required: true },
    response: { type: String, required: true },
    isCorrect: { type: Boolean, default: false },
    questionType: {
      type: String,
      enum: [
        "QUICK_TRUE_FALSE",
        "EXPANDED_TRUE_FALSE",
        "SINGLE_SELECT",
        "MULTI_SELECT",
        "VERY_SHORT_ANSWER",
        "SHORT_ANSWER",
        "LONG_ANSWER",
      ],
    },
    additionalResponses: { type: [String], default: [] },
  },
  { _id: true },
);

// SessionRegistration Schema (matches SDL SessionRegistration type)
const SessionRegistrationSchema = new Schema<ISessionRegistration>(
  {
    sessionId: { type: String, required: true },
    email: { type: String, required: true, trim: true, lowercase: true },
    name: { type: String, required: true, trim: true },
    courseTaken: { type: String, required: true, trim: true },
    level: { type: String, required: true, trim: true },
    registeredAt: { type: Date, default: Date.now },
    status: {
      type: String,
      enum: ["PENDING", "APPROVED", "REJECTED"],
      default: "PENDING",
    },
    approvalToken: { type: String, required: true, trim: true },
    approvedAt: { type: Date },
    registeredVia: {
      type: String,
      enum: ["QR_CODE", "MANUAL", "EMAIL_FORM"],
      default: "QR_CODE",
    },
  },
  { _id: true },
);

// ============================================
// MAIN SCHEMA
// ============================================

const ExamSchema = new Schema<IExam>(
  {
    title: { type: String, required: true, trim: true, maxlength: 200 },
    sessionId: { type: String, required: true, unique: true, index: true },
    accessKey: { type: String, required: true, unique: true, index: true },
    questions: [
      { type: Schema.Types.ObjectId, ref: "Question", required: true },
    ],
    difficultyDistribution: {
      type: [String],
      enum: ["EASY", "MEDIUM", "HARD"],
      required: true,
      validate: {
        validator: (v: string[]) => v && v.length > 0,
        message: "At least one difficulty level is required",
      },
    },
    examDate: { type: Date, required: true },
    timeZone: { type: String, required: true },
    participants: { type: [PreRegistrationDetailSchema], default: [] },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    createdAt: { type: Date, default: Date.now, immutable: true },

    // Optional fields
    examPreRegistrationDetails: {
      type: [PreRegistrationDetailSchema],
      default: [],
    },
    questionIdsUsed: [
      { type: Schema.Types.ObjectId, ref: "Question", default: [] },
    ],
    specialty: {
      type: String,
      enum: ["EPIDEMIOLOGY", "BIOSTATISTICS", "RESEARCH_METHODS"],
    },
    topic: { type: [String], default: [] },
    difficulty: {
      type: [String],
      enum: ["EASY", "MEDIUM", "HARD"],
      default: [],
    },
    examResponses: { type: [ExamResponseSchema], default: [] },
    questionType: {
      type: [String],
      enum: [
        "QUICK_TRUE_FALSE",
        "EXPANDED_TRUE_FALSE",
        "SINGLE_SELECT",
        "MULTI_SELECT",
        "VERY_SHORT_ANSWER",
        "SHORT_ANSWER",
        "LONG_ANSWER",
      ],
      default: [],
    },
    isAutoGenerated: { type: Boolean, default: false },
    maxParticipants: { type: Number, min: 1, max: 300, default: 300 },
    status: {
      type: String,
      enum: ["PENDING_APPROVAL", "ACTIVE", "COMPLETED", "CANCELLED"],
      default: "PENDING_APPROVAL",
      index: true,
    },
    qrPdfPath: { type: String, trim: true },

    // New fields for session workflow
    waitingList: { type: [SessionRegistrationSchema], default: [] },
    admittedParticipants: { type: [PreRegistrationDetailSchema], default: [] },
    isSessionOpen: { type: Boolean, default: false },
    sessionStartTime: { type: Date },
    sessionEndTime: { type: Date },
  },
  {
    timestamps: true,
    toJSON: {
      virtuals: true,
      transform: (doc, ret) => {
        ret.id = ret._id.toString();
        delete (ret as { _id?: any })._id;
        delete (ret as { __v?: any }).__v;
        return ret;
      },
    },
    toObject: {
      virtuals: true,
      transform: (doc, ret) => {
        ret.id = ret._id.toString();
        delete (ret as { _id?: any })._id;
        delete (ret as { __v?: any }).__v;
        return ret;
      },
    },
  },
);

// ============================================
// INDEXES
// ============================================

ExamSchema.index({ createdBy: 1, createdAt: -1 });
ExamSchema.index({ status: 1, examDate: 1 });
ExamSchema.index({ "participants.emailAddress": 1 });
ExamSchema.index({ "examPreRegistrationDetails.emailAddress": 1 });
ExamSchema.index({ "examPreRegistrationDetails.approvalToken": 1 });
ExamSchema.index({ "waitingList.email": 1 });
ExamSchema.index({ "waitingList.status": 1 });
ExamSchema.index({ sessionStartTime: 1, sessionEndTime: 1 });

// ============================================
// VIRTUALS
// ============================================

ExamSchema.virtual("participantCount").get(function (this: IExam) {
  return this.participants?.length || 0;
});

ExamSchema.virtual("availableSpots").get(function (this: IExam) {
  const maxParticipants = this.maxParticipants || 300;
  const approvedCount =
    this.examPreRegistrationDetails?.filter((reg) => reg.status === "APPROVED")
      .length || 0;
  return Math.max(0, maxParticipants - approvedCount);
});

ExamSchema.virtual("isFull").get(function (this: IExam) {
  return this.availableSpots === 0;
});

ExamSchema.virtual("pendingRegistrationsCount").get(function (this: IExam) {
  return (
    this.examPreRegistrationDetails?.filter((reg) => reg.status === "PENDING")
      .length || 0
  );
});

ExamSchema.virtual("approvedRegistrationsCount").get(function (this: IExam) {
  return (
    this.examPreRegistrationDetails?.filter((reg) => reg.status === "APPROVED")
      .length || 0
  );
});

ExamSchema.virtual("rejectedRegistrationsCount").get(function (this: IExam) {
  return (
    this.examPreRegistrationDetails?.filter((reg) => reg.status === "REJECTED")
      .length || 0
  );
});

// ============================================
// INSTANCE METHODS
// ============================================

ExamSchema.methods.isRegistrationFull = function (this: IExam): boolean {
  return this.isFull || false;
};

ExamSchema.methods.addToWaitingList = async function (
  this: IExam,
  registrationData: Partial<ISessionRegistration>,
): Promise<ISessionRegistration> {
  // Check if already in waiting list
  const existing = this.waitingList?.find(
    (reg) => reg.email === registrationData.email,
  );

  if (existing) {
    throw new Error("Email already registered in waiting list");
  }

  const newRegistration = {
    ...registrationData,
    registeredAt: new Date(),
    status: "PENDING" as WaitingListStatus,
  };

  this.waitingList = this.waitingList || [];
  this.waitingList.push(newRegistration as ISessionRegistration);
  await this.save();

  return newRegistration as ISessionRegistration;
};

ExamSchema.methods.approveWaitingListEntry = async function (
  this: IExam,
  registrationId: string,
): Promise<ISessionRegistration | null> {
  const registration = this.waitingList?.find(
    (reg) => reg._id?.toString() === registrationId,
  );

  if (!registration) {
    throw new Error("Registration not found");
  }

  if (registration.status !== "PENDING") {
    throw new Error("Registration already processed");
  }

  registration.status = "APPROVED";
  registration.approvedAt = new Date();
  await this.save();

  return registration;
};

ExamSchema.methods.rejectWaitingListEntry = async function (
  this: IExam,
  registrationId: string,
): Promise<ISessionRegistration | null> {
  const registration = this.waitingList?.find(
    (reg) => reg._id?.toString() === registrationId,
  );

  if (!registration) {
    throw new Error("Registration not found");
  }

  if (registration.status !== "PENDING") {
    throw new Error("Registration already processed");
  }

  registration.status = "REJECTED";
  await this.save();

  return registration;
};

ExamSchema.methods.admitFromWaitingList = async function (
  this: IExam,
  registrationId: string,
): Promise<IPreRegistrationDetail | null> {
  const waitingEntry = this.waitingList?.find(
    (reg) =>
      reg._id?.toString() === registrationId && reg.status === "APPROVED",
  );

  if (!waitingEntry) {
    throw new Error("No approved waiting list entry found");
  }

  if (this.isFull) {
    throw new Error("Exam is full");
  }

  // Convert to participant
  const participant: IPreRegistrationDetail = {
    sessionId: this.sessionId,
    email: waitingEntry.email,
    emailAddress: waitingEntry.email,
    name: waitingEntry.name,
    courseTaken: waitingEntry.courseTaken,
    level: waitingEntry.level,
    registeredAt: new Date(),
    status: "APPROVED",
    approvalToken: waitingEntry.approvalToken,
    registeredVia: waitingEntry.registeredVia,
    approvedAt: new Date(),
  };

  this.admittedParticipants = this.admittedParticipants || [];
  this.admittedParticipants.push(participant);

  // Also add to participants for backward compatibility
  this.participants.push(participant);

  await this.save();
  return participant;
};

ExamSchema.methods.getWaitingListStats = function (this: IExam) {
  const registrations = this.waitingList || [];
  return {
    total: registrations.length,
    pending: registrations.filter((r) => r.status === "PENDING").length,
    approved: registrations.filter((r) => r.status === "APPROVED").length,
    rejected: registrations.filter((r) => r.status === "REJECTED").length,
  };
};

ExamSchema.methods.checkAccess = function (
  this: IExam,
  email: string,
): {
  hasAccess: boolean;
  isSessionOpen: boolean;
  isTimeReached: boolean;
  message: string;
} {
  const now = new Date();
  const isTimeReached = this.sessionStartTime
    ? now >= this.sessionStartTime
    : true;
  const isSessionOpen = this.isSessionOpen || false;

  // Check if user is approved participant
  const isApproved =
    this.examPreRegistrationDetails?.some(
      (reg) =>
        (reg.email === email || reg.emailAddress === email) &&
        reg.status === "APPROVED",
    ) || false;

  const hasAccess = isApproved && isSessionOpen && isTimeReached;

  let message = "";
  if (!isApproved) message = "Not approved for this session";
  else if (!isSessionOpen) message = "Session is not open yet";
  else if (!isTimeReached) message = "Session time has not been reached";
  else message = "Access granted";

  return { hasAccess, isSessionOpen, isTimeReached, message };
};

// ============================================
// PRE-SAVE MIDDLEWARE
// ============================================

ExamSchema.pre("save", function (this: IExam, next) {
  // Set maxParticipants based on title (GROUP_REVISION sessions have 25 max)
  if (this.title && this.title.toLowerCase().includes("group revision")) {
    if (this.maxParticipants !== 25) {
      this.maxParticipants = 25;
    }
  } else if (!this.maxParticipants) {
    this.maxParticipants = 300;
  }

  // Auto-update status based on date
  const now = new Date();
  if (this.status === "ACTIVE" && this.examDate < now) {
    this.status = "COMPLETED";
  }

  next();
});

// ============================================
// STATIC METHODS
// ============================================

ExamSchema.statics.findBySessionId = function (sessionId: string) {
  return this.findOne({ sessionId });
};

ExamSchema.statics.findByAccessKey = function (accessKey: string) {
  return this.findOne({ accessKey });
};

// ============================================
// MODEL EXPORT
// ============================================

const Exam = mongoose.models.Exam || mongoose.model<IExam>("Exam", ExamSchema);

export default Exam;
